[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=0C0480694B43EE87823F86BD4E3E9F63
ProjectName=Vehicle Game Template
; Start the packaged/standalone game in stereo. Falls back to flat if no headset is connected.
bStartInVR=True

[/Script/VehicleSoundSystem.VehicleSoundSettings]
ReducedDistance=2500.000000
EngineOnlyDistance=6000.000000
CullDistance=15000.000000

